# A100 40GB optimized

name: "vits_base"

hidden_channels: 192
filter_channels: 768
n_heads: 2
n_layers: 6
kernel_size: 3
p_dropout: 0.1

n_vocab: nullspeaker_embed_dim: 256
n_speakers: 115

posterior_encoder:
    hidden_channels: 192
    out_channels: 192
    kernel_size: 5
    dilation_rate: 1
    n_layers: 16

prior_encoder:
    hidden_channels: 192
    filter_channels: 768
    n_heads: 2
    n_layers: 6
    kernel_size: 3
    p_dropout: 0.1

    flow:
        n_flows: 4
        kernel_size: 5
        dilation_rate: 1
        n_layers: 4

duration_predictor:
    hidden_channels: 256
    kernel_size: 3
    p_dropout: 0.5
    n_flows: 4
    gin_channels: 256

decoder:
    initial_channel: 512
    resblock_kernel_sizes: [3, 7, 11]
    resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
    upsample_rates: [8, 8, 2, 2]
    upsample_kernel_sizes: [16, 16, 4, 4]
    upsample_initial_channel: 256

discriminator:
    mpd:
        periods: [2, 3, 5, 7, 11]
    msd:
        scales: 3
